[package]
name = "rustodrive-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
rustodrive = { path = "../rustodrive", features = ["mock-socket"] }


[dev-dependencies]