version: '2'


services:


  amber:
    build:
      dockerfile: Dockerfile
    container_name: AMBER
    #network_mode: host
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - type: bind
        source: ../rust-client
        target: /amber-robot
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    restart: always